spring.application.name=eventmgms
spring.thymeleaf.cache=false


server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/eventmgms

spring.datasource.username=${EVENT_MGMS_DB_USERNAME}
spring.datasource.password=${EVENT_MGMS_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
